"""Generate a ready-to-run COMSOL Java model file for the benchmark (manual route).

Used when COMSOL exists but the MPh bridge fails, or on machines without Python
access to COMSOL.  The generated model is identical to the MPh-built one and ends by
saving the S-parameter table to CSV in the format compare_comsol.py ingests:
freq, Re S11, Im S11, Re S21, Im S21.
"""

from __future__ import annotations

from pathlib import Path

from . import benchmark as bm

_TEMPLATE = """\
/*
 * SCEPTRE cross-verification benchmark: WR-90 waveguide, PEC walls,
 * partial-height dielectric block (eps_r = {eps}), TE10 rectangular ports.
 * Generated by sceptre.comsol.model_gen -- geometry lives in sceptre/comsol/benchmark.py.
 *
 * Run (Windows):
 *   "{comsol_bin}\\comsolcompile.exe" SceptreBenchmark.java
 *   "{comsol_bin}\\comsolbatch.exe" -inputfile SceptreBenchmark.class
 * Output: sceptre_comsol_sparams.csv in the working directory, then:
 *   uv run python scripts/compare_comsol.py sceptre_comsol_sparams.csv
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

public class SceptreBenchmark {{

  public static Model run() {{
    Model model = ModelUtil.create("Model");
    model.component().create("comp1", true);
    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").lengthUnit("m");

    model.component("comp1").geom("geom1").create("blk_guide", "Block");
    model.component("comp1").geom("geom1").feature("blk_guide")
        .set("size", new double[]{{{a}, {b}, {ltot}}});
    model.component("comp1").geom("geom1").feature("blk_guide")
        .set("pos", new double[]{{0, 0, {zmin}}});
    model.component("comp1").geom("geom1").create("blk_diel", "Block");
    model.component("comp1").geom("geom1").feature("blk_diel")
        .set("size", new double[]{{{a}, {bh}, {blen}}});
    model.component("comp1").geom("geom1").feature("blk_diel")
        .set("pos", new double[]{{0, 0, 0}});
    model.component("comp1").geom("geom1").run();

    model.component("comp1").selection().create("sel_port1", "Box");
    model.component("comp1").selection("sel_port1").set("entitydim", 2);
    setBox(model, "sel_port1", {zmin_p1}, {zmax_p1}, {b});
    model.component("comp1").selection().create("sel_port2", "Box");
    model.component("comp1").selection("sel_port2").set("entitydim", 2);
    setBox(model, "sel_port2", {zmin_p2}, {zmax_p2}, {b});
    model.component("comp1").selection().create("sel_diel", "Box");
    model.component("comp1").selection("sel_diel").set("entitydim", 3);
    setBox(model, "sel_diel", {zmin_d}, {zmax_d}, {bh_tol});

    model.component("comp1").material().create("mat_air", "Common");
    model.component("comp1").material("mat_air").selection().all();
    model.component("comp1").material("mat_air").propertyGroup("def")
        .set("relpermittivity", new String[]{{"1"}});
    model.component("comp1").material("mat_air").propertyGroup("def")
        .set("relpermeability", new String[]{{"1"}});
    model.component("comp1").material("mat_air").propertyGroup("def")
        .set("electricconductivity", new String[]{{"0"}});
    model.component("comp1").material().create("mat_diel", "Common");
    model.component("comp1").material("mat_diel").selection().named("sel_diel");
    model.component("comp1").material("mat_diel").propertyGroup("def")
        .set("relpermittivity", new String[]{{"{eps}"}});
    model.component("comp1").material("mat_diel").propertyGroup("def")
        .set("relpermeability", new String[]{{"1"}});
    model.component("comp1").material("mat_diel").propertyGroup("def")
        .set("electricconductivity", new String[]{{"0"}});

    model.component("comp1").physics().create("emw", "ElectromagneticWaves", "geom1");
    model.component("comp1").physics("emw").create("port1", "Port", 2);
    model.component("comp1").physics("emw").feature("port1").selection().named("sel_port1");
    model.component("comp1").physics("emw").feature("port1").set("PortType", "Rectangular");
    model.component("comp1").physics("emw").feature("port1").set("PortExcitation", "on");
    model.component("comp1").physics("emw").create("port2", "Port", 2);
    model.component("comp1").physics("emw").feature("port2").selection().named("sel_port2");
    model.component("comp1").physics("emw").feature("port2").set("PortType", "Rectangular");
    model.component("comp1").physics("emw").feature("port2").set("PortExcitation", "off");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").feature("size").set("custom", "on");
    model.component("comp1").mesh("mesh1").feature("size").set("hmax", {mesh_air});
    model.component("comp1").mesh("mesh1").create("siz_diel", "Size");
    model.component("comp1").mesh("mesh1").feature("siz_diel").selection().geom("geom1", 3);
    model.component("comp1").mesh("mesh1").feature("siz_diel").selection().named("sel_diel");
    model.component("comp1").mesh("mesh1").feature("siz_diel").set("custom", "on");
    model.component("comp1").mesh("mesh1").feature("siz_diel").set("hmaxactive", true);
    model.component("comp1").mesh("mesh1").feature("siz_diel").set("hmax", {mesh_diel});
    model.component("comp1").mesh("mesh1").create("ftet", "FreeTet");
    model.component("comp1").mesh("mesh1").run();

    model.study().create("std1");
    model.study("std1").create("freq", "Frequency");
    model.study("std1").feature("freq").set("plist", "{plist}");
    // Bind the ports to the study step -- without this the API-built port is inert.
    model.component("comp1").physics("emw").feature("port1").set("StudyStep", "std1/freq");
    model.component("comp1").physics("emw").feature("port2").set("StudyStep", "std1/freq");
    try {{
      model.study("std1").run();
    }} catch (Exception e) {{
      // Iterative (multigrid/SOR) solver can fail on this high-contrast model;
      // fall back to the default direct solver.
      model.sol("sol1").feature("s1").feature("fc1").set("linsolver", "dDef");
      model.sol("sol1").runAll();
    }}

    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", new String[]{{
        "freq", "real(emw.S11)", "imag(emw.S11)", "real(emw.S21)", "imag(emw.S21)"}});
    model.result().table().create("tbl1", "Table");
    model.result().numerical("gev1").set("table", "tbl1");
    model.result().numerical("gev1").setResult();
    model.result().table("tbl1").save("sceptre_comsol_sparams.csv");
    return model;
  }}

  private static void setBox(Model model, String tag, double zmin, double zmax, double ymax) {{
    model.component("comp1").selection(tag).set("xmin", {xtol_neg});
    model.component("comp1").selection(tag).set("xmax", {xtol_pos});
    model.component("comp1").selection(tag).set("ymin", {xtol_neg});
    model.component("comp1").selection(tag).set("ymax", ymax + 1.0E-6);
    model.component("comp1").selection(tag).set("zmin", zmin);
    model.component("comp1").selection(tag).set("zmax", zmax);
    model.component("comp1").selection(tag).set("condition", "inside");
  }}

  public static void main(String[] args) {{
    run();
  }}
}}
"""


def write_java(
    out_path: str | Path,
    comsol_bin: str = r"C:\Program Files\COMSOL\COMSOL61\Multiphysics\bin\win64",
    case: bm.BenchmarkCase = bm.STANDARD,
) -> Path:
    tol = 1e-6
    text = _TEMPLATE.format(
        a=bm.A,
        b=bm.B,
        bh=case.block_height,
        bh_tol=case.block_height,
        blen=case.block_len,
        ltot=case.block_len + 2 * bm.LEAD_LEN,
        zmin=-bm.LEAD_LEN,
        zmin_p1=-bm.LEAD_LEN - tol,
        zmax_p1=-bm.LEAD_LEN + tol,
        zmin_p2=case.block_len + bm.LEAD_LEN - tol,
        zmax_p2=case.block_len + bm.LEAD_LEN + tol,
        zmin_d=-tol,
        zmax_d=case.block_len + tol,
        eps=case.eps_block,
        mesh_air=case.mesh_air,
        mesh_diel=case.mesh_diel,
        plist=" ".join(f"{f:.10g}[Hz]" for f in bm.frequencies(case)),
        comsol_bin=comsol_bin,
        xtol_neg=-tol,
        xtol_pos=bm.A + tol,
    )
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return out
